export enum RoleName {
  ADMIN = 'ADMIN',
  SALES_STAFF = 'SALES_STAFF',
  GODOWN_MANAGER = 'GODOWN_MANAGER',
  DRIVER = 'DRIVER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum DriverDutyStatus {
  OFF_DUTY = 'OFF_DUTY',
  AVAILABLE = 'AVAILABLE',
  JOB_OFFERED = 'JOB_OFFERED',
  BUSY = 'BUSY',
  AT_PICKUP = 'AT_PICKUP',
  LOADING = 'LOADING',
  IN_TRANSIT = 'IN_TRANSIT',
  AT_DELIVERY = 'AT_DELIVERY',
  UNLOADING = 'UNLOADING',
  RETURNING = 'RETURNING',
  BREAK = 'BREAK',
  SUSPENDED = 'SUSPENDED',
  OFFLINE = 'OFFLINE',
}

export enum VehicleStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  IN_TRIP = 'IN_TRIP',
  MAINTENANCE = 'MAINTENANCE',
  INACTIVE = 'INACTIVE',
}

export enum LocationType {
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
  GODOWN = 'GODOWN',
  OTHER = 'OTHER',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  RECEIVED = 'RECEIVED',
  DISPATCH_PENDING = 'DISPATCH_PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum JobType {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
  TRANSFER = 'TRANSFER',
  RETURN = 'RETURN',
}

export enum JobStatus {
  DRAFT = 'DRAFT',
  OFFERED = 'OFFERED',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum StopType {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
  GODOWN = 'GODOWN',
  RETURN = 'RETURN',
}

export enum StopStatus {
  PENDING = 'PENDING',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum JobRejectReason {
  VEHICLE_CAPACITY = 'VEHICLE_CAPACITY',
  VEHICLE_UNAVAILABLE = 'VEHICLE_UNAVAILABLE',
  DRIVER_UNAVAILABLE = 'DRIVER_UNAVAILABLE',
  ALREADY_COMMITTED = 'ALREADY_COMMITTED',
  PERSONAL_REASON = 'PERSONAL_REASON',
  OTHER = 'OTHER',
}

export enum DeliveryFailureReason {
  CUSTOMER_CLOSED = 'CUSTOMER_CLOSED',
  CUSTOMER_REFUSED = 'CUSTOMER_REFUSED',
  WRONG_ADDRESS = 'WRONG_ADDRESS',
  CUSTOMER_UNAVAILABLE = 'CUSTOMER_UNAVAILABLE',
  VEHICLE_BREAKDOWN = 'VEHICLE_BREAKDOWN',
  GOODS_DAMAGED = 'GOODS_DAMAGED',
  GOODS_UNAVAILABLE = 'GOODS_UNAVAILABLE',
  OTHER = 'OTHER',
}

export enum PermissionCode {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DISABLE = 'USER_DISABLE',
  DRIVER_DUTY_TOGGLE = 'DRIVER_DUTY_TOGGLE',
  VEHICLE_CREATE = 'VEHICLE_CREATE',
  VEHICLE_UPDATE = 'VEHICLE_UPDATE',
  LOCATION_CREATE = 'LOCATION_CREATE',
  LOCATION_UPDATE = 'LOCATION_UPDATE',
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  JOB_DISPATCH = 'JOB_DISPATCH',
  JOB_REASSIGN = 'JOB_REASSIGN',
  JOB_ACCEPT_REJECT = 'JOB_ACCEPT_REJECT',
  JOB_EXECUTE = 'JOB_EXECUTE',
  GPS_VIEW_ALL = 'GPS_VIEW_ALL',
  GPS_VIEW_ASSIGNED = 'GPS_VIEW_ASSIGNED',
  GPS_INGEST = 'GPS_INGEST',
  POD_UPLOAD = 'POD_UPLOAD',
  REPORT_VIEW = 'REPORT_VIEW',
  AUDIT_VIEW = 'AUDIT_VIEW',
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
}
